Add redis image to docker compose and change workflow to use compose

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -145,8 +145,15 @@ jobs:
       - name: SSH into EC2 instance
         run: |
           ssh -i ~/.ssh/key.pem ec2-user@${{ steps.ec2-ip.outputs.ec2_public_ip }} << 'EOF'
-            docker pull public.ecr.aws/${{ env.ECR_REGISTRY_ALIAS }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
-            docker run -d -p80:5000 public.ecr.aws/${{ env.ECR_REGISTRY_ALIAS }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
+          
+          export APP_IMAGE=public.ecr.aws/${{ env.ECR_REGISTRY_ALIAS }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
+
+          docker pull ${APP_IMAGE}
+          docker pull redis:alpine
+
+          curl -o docker-compose.yaml https://raw.githubusercontent.com/Karen-W-2002/CloudPipe/main/docker-compose.yaml
+
+          docker compose up -d
           EOF
 
     outputs:
@@ -165,6 +172,21 @@ jobs:
           for i in {1..5}; do
             curl --fail http://${{ needs.deploy.outputs.ec2_public_ip }}/ && break
             sleep 10
+            if [$i -eq 5]; then
+              echo "Health check failed after 5 attempts"
+              exit 1
+            fi
+          done
+
+      - name: DB health check
+        run: |
+          for i in {1..5}; do
+            curl --fail http://${{ needs.deploy.outputs.ec2_public_ip }}/health && break
+            sleep 10
+            if [$i -eq 5]; then
+              echo "DB health check failed after 5 attempts"
+              exit 1
+            fi
           done
 
   destroy:
